config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: "pages#profile"
  resources 'quizzs', only: %i[show new create update delete] do
    resources 'questions', only: %i[new create edit update delete] do
      resources 'answers', only: %i[new create edit update delete]
    end
    resources 'results', only: :create
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quizz
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
end

app/models/quizz.rb
class Quizz < ApplicationRecord
  DIFFICULTY = %w[easy medium hard]
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions
  has_many :results
  validates_length_of :questions, maximum: 3
  validates :title, :description, presence: true
  validates :difficulty, acceptance: { accept: DIFFICULTY }, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :quizz
  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :results, dependent: :destroy

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def authorize_admin
    redirect_to root_path, alert: "Not authorized" if current_user.try(:admin) == false
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_quizzs, only: %i[home profile]

  def home() end

  def profile() end

  private

  def set_quizzs
    @quizzs = Quizz.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize_admin, only: %i[new create edit update delete]
  before_action :set_quizz, only: %i[new create]

  def new
    @question = Question.new
    4.times do
      @question.answers.build
    end
  end

  def create
    @question = Question.new(question_params)
    @question.quizz = @quizz
    if @question.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity, alert: 'Missing information'
    end
  end

  private

  def set_quizz
    @quizz = Quizz.find(params[:quizz_id])
  end

  def question_params
    params.require(:question).permit(:title, answers_attributes: %i[title status question_id])
  end
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  before_action :set_quizz, :set_questions, only: %i[show update]
  before_action :authorize_admin, only: %i[new create delete]
  def show() end

  def new
    @quizz = Quizz.new
  end

  def create
    @quizz = Quizz.new(quizz_params)
    if @quizz.save
      redirect_to new_quizz_question_path(@quizz), notice: 'Created Successfully'
    else
      render :new, status: :unprocessable_entity, alert: 'Something went wrong'
    end
  end

  def update
    quizz_score = CalculateScoreService.new(params[:quizz], @quizz).call
    total_score = @quizz.score << quizz_score
    @quizz.update(score: total_score)
    @result = Result.create(user: current_user, quizz: @quizz, score: quizz_score)
    if quizz_score >= 2
      redirect_to root_path, notice: "You passed #{quizz_score} on 3"
    else
      redirect_to root_path, notice: "You failed the quizz"
    end
  end

  private

  def set_quizz
    @quizz = Quizz.find(params[:id])
  end

  def set_questions
    @questions = @quizz.questions
  end

  def quizz_params
    params.require(:quizz).permit(:title, :description, :difficulty)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/color_helper.rb
module ColorHelper
  def color(difficulty)
    color = ""
    if difficulty == "medium"
      color = "#FF9F29"
    elsif difficulty == "easy"
      color = "#93c47d"
    elsif difficulty == "hard"
      color = "#F44336"
    end
    return color
  end

  def background_color(difficulty)
    color = ""
    if difficulty == "medium"
      color = "#FF9F2920"
    elsif difficulty == "easy"
      color = "#93c47d20"
    elsif difficulty == "hard"
      color = "#F4433620"
    end
    return color
  end

  def passed(score)
    score >= 2 ? "#93c47d" : "#F44336"
  end

  def background_passed(score)
    score >= 2 ? "#93c47d20" : "#F4433620"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyAdvisorTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1 class="ps-3 my-5 text-center">Quizz Yourself</h1>
    <div class="container-cards-home">
      <% @quizzs.each do |quizz| %>
        <% unless quizz.questions.empty? %>
          <%= link_to quizz_path(quizz), class: 'quizzs-home' do  %>
            <div class="card p-3 m-3 cards-home align-items-center">
              <h3 class="text-center"><%= quizz.title %></h3>
              <p class="text-center"><%= quizz.description %></p>
              <p class="difficulty" style="--color: <%= color(quizz.difficulty) %>; --background: <%= background_color(quizz.difficulty) %>"><%= quizz.difficulty.capitalize %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/pages/profile.html.erb
<div class="container text-center">

    <div class="d-flex justify-content-end">
      <% if current_user.admin? %>
        <%= link_to 'Add Quizz', new_quizz_path, class: 'btn btn-success mt-3' %>
      <% end %>
    </div>

    <h1 class="ps-3 my-5">My Results</h1>

    <div class="score-container">
      <% @quizzs.each do |quizz| %>
        <% unless quizz.questions.empty? %>
          <div class="card p-3 m-3 card-score">
            <h3 class="py-2"><%= quizz.title %></h3>
            <% results = Result.where(user: current_user, quizz: quizz).pluck(:score) %>
            <% if results.empty? %>
                <p>You don't have any score yet</p>
            <% else %>
              <% results.each do |score| %>
                <p>Your score was <strong><%= score %></strong> <span class="passed px-2" style="--passed: <%= passed(score) %>; --background: <%= background_passed(score) %>"><%= score >= 2 ? "Passed" : "Failed" %></span></p>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <h1>Add Questions & Answers</h1>

  <%= simple_form_for [@quizz, @question], html: {multipart: true} do |f| %>
      <div class="card p-4 my-4">
        <%= f.input :title, label: 'Question 1', input_html: { name: "question[title1]" } %>
        <% 4.times do %>
          <%= f.fields_for :answers, Answer.new do |fa| %>
            <%= fa.input :title, label: 'Answer' %>
            <%= fa.input :status, as: :boolean, label: 'Good Answer' %>
          <% end %>
        <% end %>
      </div>
      <div class="card p-4 my-4">
        <%= f.input :title, label: 'Question 2', input_html: { name: "question[title2]" } %>
        <% 4.times do %>
          <%= f.fields_for :answers, Answer.new do |fa| %>
            <%= fa.input :title, label: 'Answer' %>
            <%= fa.input :status, as: :boolean, label: 'Good Answer' %>
          <% end %>
        <% end %>
      </div>
      <div class="card p-4 my-4">
        <%= f.input :title, label: 'Question 3', input_html: { name: "question[title3]" } %>
        <% 4.times do %>
          <%= f.fields_for :answers, Answer.new do |fa| %>
            <%= fa.input :title, label: 'Answer' %>
            <%= fa.input :status, as: :boolean, label: 'Good Answer' %>
          <% end %>
        <% end %>
      </div>
    <%= f.submit 'All Done', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/quizzs/new.html.erb
<div class="container">
  <h1>Add Quizz Here</h1>

  <%= simple_form_for(@quizz) do |f| %>
    <%= f.input :title, placeholder: 'Python Quizz' %>
    <%= f.input :description, placeholder: "The best quizz to test your python's knowledge" %>
    <%= f.select :difficulty, Quizz::DIFFICULTY %>
    <%= f.submit 'All Done', class: 'btn btn-success' %>
  <% end %>

</div>

app/views/quizzs/show.html.erb
<div class="container text-center">
  <h1 class="ps-3 my-5"><%= @quizz.title %></h1>

  <div class="form-container">
    <div class="p-3 m-3 text-center w-75">
      <%= simple_form_for(@quizz) do |f| %>
        <% @questions.each do |question| %>
          <div class="card p-3 mb-4 card-question">
            <h4><%= question.title %></h4>
            <%= f.association :answers, as: :check_boxes, collection: Answer.where(question_id: question.id),
                              checked: false, label: "", input_html: { class: "toggle d-none my-3" } %>
          </div>
        <% end %>
        <%= f.submit 'Done', class: 'm-3 btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "question_logo.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Profile", profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, class: "nav-link", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>